add support for libjpeg-turbo and deprecate jpeg option
bincrafters/conan-imagemagick pull request #7
Opened 2020-10-27 21:17 UTC by Renari

2020-11-09 13:46 UTC, Renari commented
It looks like this build is failing due to linking issues with openjp2 and openexr.

2020-11-11 19:59 UTC, uilianries requested changes

2020-11-11 19:59 UTC, uilianries commented on conanfile.py
> +               "with_libjpeg": [True, False, "libjpeg-turbo"]}
```suggestion
               "with_libjpeg": [False, "libjpeg", "libjpeg-turbo"]}
```

We had a similar discussion on Conan Center Index few days ago [here](https://github.com/conan-io/conan-center-index/pull/2730).

2020-11-13 18:59 UTC, uilianries reviewed
small fix required

2020-11-13 18:59 UTC, uilianries commented on conanfile.py
> +                       "with_libjpeg": True,
```suggestion
                       "with_libjpeg": "libjpeg",
```

2020-11-13 20:09 UTC, Renari commented
```
        # Handle deprecated jpeg option
        if self.options.jpeg and not self.options.with_libjpeg:
            self.output.warn("jpeg option is deprecated, use with_libjpeg option instead.")
            self.options.with_libjpeg = True
        del self.options.jpeg
```
This no longer works with the above changes due to `with_libjpeg` now having a default option. I think we can change the default for the `jpeg` option to `False` and then check if it's set to true and show the warning instead, since that means the option was being set by the user.

2021-10-08 13:01 UTC, Croydon commented
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

https://conan.io/center/imagemagick

2021-10-08 13:01 UTC, closed without merging